// Builds dist/worker.js: one self-contained file you can paste into the Cloudflare dashboard
// or deploy with `npx wrangler deploy`. No dependencies.
//
// It inlines everything in public/ and the bus stop list from stops/stops.json.

import { readFile, writeFile, readdir, mkdir } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.dirname(fileURLToPath(import.meta.url));
const MIME = {
  '.html': 'text/html; charset=utf-8', '.js': 'text/javascript; charset=utf-8', '.css': 'text/css; charset=utf-8',
  '.json': 'application/json', '.svg': 'image/svg+xml', '.webmanifest': 'application/manifest+json',
};

const assets = {};
for (const name of await readdir(path.join(root, 'public'))) {
  const type = MIME[path.extname(name)];
  if (!type) { console.warn(`skipping public/${name} (not a text file type this build knows)`); continue; }
  assets[`/${name}`] = { type, body: await readFile(path.join(root, 'public', name), 'utf8') };
}

// The stop list is a committed snapshot (stops/stops.json: [code, name, road] per stop). Refresh it with `npm run stops`.
// STOPS_FILE and OUT_FILE let the tests build a small bundle somewhere else.
const stopsFile = process.env.STOPS_FILE || path.join(root, 'stops', 'stops.json');
let stops;
try {
  stops = JSON.parse(await readFile(stopsFile, 'utf8'));
  if (!Array.isArray(stops) || !stops.length) throw new Error('empty');
} catch {
  console.error(`Could not read the stop list at ${stopsFile}. Run "npm run stops" (needs LTA_ACCOUNT_KEY in .env) to create it.`);
  process.exit(1);
}

const template = await readFile(path.join(root, 'worker.template.js'), 'utf8');
const fill = (src, marker, value) => {
  if (src.split(marker).length !== 2) throw new Error(`marker ${marker} not found exactly once`);
  return src.replace(marker, () => JSON.stringify(value));
};
// The stamp shown at /api/status: build time, plus the commit when built by the pipeline.
const sha = (process.env.GIT_SHA || '').slice(0, 7);
const build = new Date().toISOString().slice(0, 16).replace('T', ' ') + ' UTC' + (sha ? ` (${sha})` : '');
// The page carries the same stamp, so an open app can tell when the server has a newer version than the one it is running.
assets['/app.js'].body = fill(assets['/app.js'].body, "/*__APP_BUILD__*/'dev'", build);
let out = fill(template, '/*__ASSETS__*/{}', assets);
out = fill(out, '/*__STOPS__*/[]', stops);
out = fill(out, "/*__BUILD__*/'dev'", build);
out = out.replace('// This is the SOURCE. Run `node build-worker.mjs` to produce dist/worker.js, which is what you deploy.',
  () => `// GENERATED by build-worker.mjs on ${new Date().toISOString().slice(0, 10)}. Edit worker.template.js or public/, then rebuild.`);

const outFile = process.env.OUT_FILE || path.join(root, 'dist', 'worker.js');
await mkdir(path.dirname(outFile), { recursive: true });
await writeFile(outFile, out);
console.log(`build ${build}`);
console.log(`${path.relative(root, outFile)} written: ${(out.length / 1024).toFixed(0)} KB, ${Object.keys(assets).length} files, ${stops.length} stops`);
